---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: castle
spec:
  type: NodePort
  ports:
  - name: "8848"
    port: 8848
    targetPort: 8848
    nodePort: 30848
  - name: "9848"
    port: 9848
    targetPort: 9848
  selector:
    service: nacos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: castle
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nacos
  template:
    metadata:
      labels:
        service: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.1.0
        resources:
          requests:
            cpu: 2000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        env:
          - name: SPRING_DATASOURCE_PLATFORM
            value: "mysql"
          - name: MODE
            value: "standalone"
          - name: MYSQL_MASTER_SERVICE_HOST
            value: "mysql.castle"
          - name: MYSQL_MASTER_SERVICE_PORT
            value: "3306"
          - name: MYSQL_MASTER_SERVICE_USER
            value: "root"
          - name: MYSQL_MASTER_SERVICE_PASSWORD
            value: "root@0808"
          - name: MYSQL_MASTER_SERVICE_DB_NAME
            value: "nacos_config"
      restartPolicy: Always