apiVersion: v1
kind: Config
clusters:
- name: "sc01-k8s-cluster01"
  cluster:
    server: "https://100.64.51.10/k8s/clusters/local"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQ\
      VM2Z0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpJdwpNekk1TVRJeE5UTTBXaGNOTXpJd016STJNVEl4TlRNMFdqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFRK3ZPTHdIYzBMW\
      lEra01jb3FoVlc5ZWRlNkt3QkkrRysybFA0VDFLaApKSVJIVm5ueGc2MkJlbmd3dlNocHNTTWF3Z\
      EtVMkQzVjZzRE9GRmZKdzJLeG95TXdJVEFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBeDFIUGpoK2IKZVBoSTE0Y3phQ\
      i9rLzRxUWxEdlQ5eXdqeG9pT2lGMW9zb0FDSUhIWDVocUlIM2dCeThBNUlzM29PM2R4MGRxVwpVe\
      itVbTRzbGVKYkZCL3BpCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="

users:
- name: "sc01-k8s-cluster01"
  user:
    token: "kubeconfig-u-h7iqvimyxf:g4m57sxst766c8qxbll4kqzg8wx6rxvwphvf88575xr5n4d8f8x7jb"


contexts:
- name: "sc01-k8s-cluster01"
  context:
    user: "sc01-k8s-cluster01"
    cluster: "sc01-k8s-cluster01"

current-context: "sc01-k8s-cluster01"