---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: castle
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30336
  selector:
    service: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: castle
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  template:
    metadata:
      labels:
        service: mysql
    spec:
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-conf
      containers:
      - name: redis
        image: 100.64.10.37/devops/mysql:5.7
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/mysql.conf
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root@0808"
      restartPolicy: Always
