---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: castle
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    service: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: castle
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
      - name: redis
        image: 100.64.10.37/devops/redis:6.0.2
      restartPolicy: Always
